package xyz.iwolfking.woldsvaults.datagen;

import iskallia.vault.config.customisation.CustomisationDiscovery;
import iskallia.vault.config.customisation.GreedChallengeDiscovery;
import iskallia.vault.config.customisation.VaultLevelDiscovery;
import net.minecraft.data.DataGenerator;
import net.minecraft.network.chat.Component;
import net.minecraft.server.level.ServerPlayer;
import xyz.iwolfking.vhapi.api.datagen.AbstractPlayerTitlesProvider;
import xyz.iwolfking.woldsvaults.WoldsVaults;
import xyz.iwolfking.woldsvaults.api.core.discovery.customisation.ArtifactCustomisationDiscovery;
import xyz.iwolfking.woldsvaults.api.core.discovery.customisation.HeraldCustomisationDiscovery;
import xyz.iwolfking.woldsvaults.api.core.discovery.customisation.ThemeCustomisationDiscovery;

import java.util.Map;
import java.util.function.Consumer;

public class ModPlayerTitlesProvider extends AbstractPlayerTitlesProvider {
    public ModPlayerTitlesProvider(DataGenerator generator) {
        super(generator, WoldsVaults.MOD_ID);
    }


    @Override
    protected void buildModifiers() {
        addPrefix("eternal_prefix", "Eternal ", "#2ECC71", 2, new VaultLevelDiscovery(100));
        addPrefix("riftborn_prefix", "Riftborn ", "#8E44AD", 2, new ArtifactCustomisationDiscovery(9));
        addPrefix("dreadknight_prefix", "Dreadknight ", "#4B0082", 2, new VaultLevelDiscovery(75));
        addPrefix("ironbound_prefix", "Ironbound ", "#5A5A5A", 2, new VaultLevelDiscovery(10));
        addPrefix("warden_prefix", "Warden ", "#2E4053", 2, new ThemeCustomisationDiscovery("Void"));
        addPrefix("hollow_prefix", "Hollow ", "#1B2631", 2, new ThemeCustomisationDiscovery("Sporegrove"));
        addPrefix("quantum_prefix", "Quantum ", "#BB8FCE", 2, new ThemeCustomisationDiscovery("Void"));
        addPrefix("celestial_prefix", "Celestial ", "#A3E4D7", 4, new ThemeCustomisationDiscovery("Gods"));
        addPrefix("ashen_prefix", "Ashen ", "#A6ACAF", 2, new ThemeCustomisationDiscovery("Nether"));
        addPrefix("runewrought_prefix", "Runewrought ", "#D7BDE2", 3, new ArtifactCustomisationDiscovery(5));
        addPrefix("stormforged_prefix", "Stormforged ", "#5DADE2", 4,new ArtifactCustomisationDiscovery(10));
        addPrefix("gilded_prefix", "Gilded ", "#F7DC6F", 3, new ArtifactCustomisationDiscovery(20));
        addPrefix("soulbound_prefix", "Soulbound ", "#884EA0", 4, new ArtifactCustomisationDiscovery(24));
        addPrefix("radiant_prefix", "Radiant ", "#FDEBD0", 2, new ThemeCustomisationDiscovery("Sandsworn"));
        addPrefix("echoing_prefix", "Echoing ", "#AEB6BF", 2, new ThemeCustomisationDiscovery("Void"));
        addPrefix("nethersteel_prefix", "Nethersteel ", "#922B21", 3, new ThemeCustomisationDiscovery("Nether"));
        addPrefix("gravemind_prefix", "Gravemind ", "#1C2833", 2, new ThemeCustomisationDiscovery("Bloodveil"));
        addPrefix("auric_prefix", "Auric ", "#F4D03F", 3, new ArtifactCustomisationDiscovery(3));
        addPrefix("shattered_prefix", "Shattered ", "#99A3A4", 2,new ThemeCustomisationDiscovery("LostDepths"));
        addPrefix("emberborn_prefix", "Emberborn ", "#E74C3C", 3, new ThemeCustomisationDiscovery("Nether"));
        addPrefix("skyborne_prefix", "Skyborne ", "#5DADE2", 2,new ThemeCustomisationDiscovery("Aether"));
        addPrefix("forlorn_prefix", "Forlorn ", "#566573", 2, new ThemeCustomisationDiscovery("LostDepths"));
        addPrefix("verdant_prefix", "Verdant ", "#58D68D", 3, new ThemeCustomisationDiscovery("Glimmergrove"));
        addPrefix("lunarcrown_prefix", "Lunarcrown ", "#D2B4DE", 4,new ThemeCustomisationDiscovery("Space"));
        addPrefix("tempest_prefix", "Tempest ", "#2471A3", 3, new ArtifactCustomisationDiscovery(7));
        addPrefix("hellforged_prefix", "Hellforged ", "#8B0000", 4, new ThemeCustomisationDiscovery("Nether"));
        addPrefix("demonbound_prefix", "Demonbound ", "#7D1B1B", 2, new ThemeCustomisationDiscovery("Nether"));
        addPrefix("voidspawn_prefix", "Voidspawn ", "#4A0E0E", 2, new ThemeCustomisationDiscovery("Void"));
        addPrefix("blightfire_prefix", "Blightfire ", "#A93226", 2, new ThemeCustomisationDiscovery("Nether"));
        addPrefix("malignant_prefix", "Malignant ", "#641E16", 2, new ThemeCustomisationDiscovery("Grimdark"));
        addPrefix("bloodrot_prefix", "Bloodrot ", "#922B21", 2, new ThemeCustomisationDiscovery("Bloodveil"));
        addPrefix("netherborn_prefix", "Netherborn ", "#C0392B", 3, new ThemeCustomisationDiscovery("Nether"));
        addPrefix("soulmaw_prefix", "Soulmaw ", "#4D0F0F", 2, new ThemeCustomisationDiscovery("Nether"));
        addPrefix("fiendforged_prefix", "Fiendforged ", "#7C0A02", 3, new ThemeCustomisationDiscovery("Nether"));
        addPrefix("scarletflame_prefix", "Scarletflame ", "#B03A2E", 2, new ThemeCustomisationDiscovery("Nether"));
        addPrefix("nightmarish_prefix", "Nightmarish ", "#5A0000", 2, new ThemeCustomisationDiscovery("Grimdark"));
        addPrefix("hatespawn_prefix", "Hatespawn ", "#6E2C2C", 2, new ThemeCustomisationDiscovery("Grimdark"));
        addPrefix("warpfire_prefix", "Warpfire ", "#FF3300", 3, new ThemeCustomisationDiscovery("Grimdark"));
        addPrefix("seraphic_prefix", "Seraphic ", "#FADBD8", 4, new ThemeCustomisationDiscovery("Gods"));
        addPrefix("radiant_prefix", "Radiant ", "#F9E79F", 3, new ThemeCustomisationDiscovery("Sandsworn"));
        addPrefix("divinity_prefix", "Divinity ", "#F7DC6F", 4, new ThemeCustomisationDiscovery("Gods"));
        addPrefix("haloed_prefix", "Haloed ", "#FFF8DC", 2, new ThemeCustomisationDiscovery("Gods"));
        addPrefix("archon_prefix", "Archon ", "#FDEDEC", 3, new ThemeCustomisationDiscovery("Gods"));
        addPrefix("luminous_prefix", "Luminous ", "#F4ECF7", 3, new ArtifactCustomisationDiscovery(20));
        addPrefix("sanctified_prefix", "Sanctified ", "#EBF5FB", 2, new ThemeCustomisationDiscovery("Gods"));
        addPrefix("ethereal_prefix", "Ethereal ", "#E8F8F5", 3, new ThemeCustomisationDiscovery("Gods"));
        addPrefix("dawnforged_prefix", "Dawnforged ", "#FFF2CC", 3, new ThemeCustomisationDiscovery("Gods"));
        addPrefix("hallowed_prefix", "Hallowed ", "#FDEBD0", 2, new ThemeCustomisationDiscovery("Gods"));
        addPrefix("gracebound_prefix", "Gracebound ", "#FBEEE6", 2, new ThemeCustomisationDiscovery("Gods"));
        addPrefix("auroral_prefix", "Auroral ", "#FEF9E7", 2, new ThemeCustomisationDiscovery("Gods"));
        addPrefix("solarian_prefix", "Solarian ", "#FFF4B0", 4, new ThemeCustomisationDiscovery("Sandsworn"));
        addPrefix("astral_prefix", "Astral ", "#A569BD", 3, new ArtifactCustomisationDiscovery(25));
        addPrefix("cosmic_prefix", "Cosmic ", "#7FB3D5", 3, new ArtifactCustomisationDiscovery(25));
        addPrefix("voidborn_prefix", "Voidborn ", "#1C1C3C", 4, new ThemeCustomisationDiscovery("Void"));
        addPrefix("galactic_prefix", "Galactic ", "#5DADE2", 3, new ThemeCustomisationDiscovery("Space"));
        addPrefix("nebular_prefix", "Nebular ", "#AF7AC5", 2, new ThemeCustomisationDiscovery("Space"));
        addPrefix("quantumstar_prefix", "Quantumstar ", "#7845FF", 4,new ThemeCustomisationDiscovery("Space"));
        addPrefix("darkmatter_prefix", "Darkmatter ", "#0B0B0F", 4,new ThemeCustomisationDiscovery("Space"));
        addPrefix("supernova_prefix", "Supernova ", "#F1948A", 3,new ThemeCustomisationDiscovery("Space"));
        addPrefix("eventide_prefix", "Eventide ", "#566573", 2,new ThemeCustomisationDiscovery("Underwater"));
        addPrefix("astron_prefix", "Astron ", "#85929E", 2,new ThemeCustomisationDiscovery("Space"));
        addPrefix("chronos_prefix", "Chronos ", "#AAB7B8", 3,new ThemeCustomisationDiscovery("Space"));
        addPrefix("gravitybound_prefix", "Gravitybound ", "#34495E", 3,new ThemeCustomisationDiscovery("Space"));
        addPrefix("interstellar_prefix", "Interstellar ", "#566DF0", 4,new ThemeCustomisationDiscovery("Space"));
        addPrefix("cosmograd_prefix", "Cosmograd ", "#BB8FCE", 3,new ThemeCustomisationDiscovery("Space"));
        addPrefix("buccaneer_prefix", "Buccaneer ", "#C49A6C", 2, new ThemeCustomisationDiscovery("Saltshade"));
        addPrefix("corsair_prefix", "Corsair ", "#8E6B3A", 3, new ThemeCustomisationDiscovery("Saltshade"));
        addPrefix("dreadpirate_prefix", "Dreadpirate ", "#4A3728", 3, new ThemeCustomisationDiscovery("Saltshade"));
        addPrefix("salted_prefix", "Salted ", "#B0C4DE", 1, new ThemeCustomisationDiscovery("Saltshade"));
        addPrefix("searavager_prefix", "Sea-Ravager ", "#6E6658", 2, new ThemeCustomisationDiscovery("Saltshade"));
        addPrefix("blackflag_prefix", "Black-Flag ", "#0D0D0D", 4, new ThemeCustomisationDiscovery("Saltshade"));
        addPrefix("ironhook_prefix", "Ironhook ", "#7F8C8D", 2, new ThemeCustomisationDiscovery("Tropics"));
        addPrefix("rumsoaked_prefix", "Rum-Soaked ", "#A0522D", 2, new ThemeCustomisationDiscovery("Tropics"));
        addPrefix("krakenbound_prefix", "Krakenbound ", "#2E4053", 3, new ThemeCustomisationDiscovery("Tropics"));
        addPrefix("mariner_prefix", "Mariner ", "#5D6D7E", 2, new ThemeCustomisationDiscovery("Tropics"));
        addPrefix("stormtide_prefix", "Stormtide ", "#34495E", 3, new ThemeCustomisationDiscovery("Tropics"));
        addPrefix("cutlass_prefix", "Cutlass ", "#9E9E9E", 2, new ThemeCustomisationDiscovery("Tropics"));
        addPrefix("tidereaver_prefix", "Tidereaver ", "#1B4F72", 3, new ThemeCustomisationDiscovery("Tropics"));
        addPrefix("scallywag_prefix", "Scallywag ", "#C29F66", 1, new ThemeCustomisationDiscovery("Tropics"));
        addPrefix("oceanborn_prefix", "Oceanborn ", "#567D8C", 2, new ThemeCustomisationDiscovery("Underwater"));
        addPrefix("crystalline_prefix", "Crystalline ", "#AEE5F8", 3, new ThemeCustomisationDiscovery("Deepcrag"));
        addPrefix("shardbound_prefix", "Shardbound ", "#8FD3E8", 2, new ThemeCustomisationDiscovery("Deepcrag"));
        addPrefix("gemcarved_prefix", "Gemcarved ", "#D7BDE2", 3, new ThemeCustomisationDiscovery("Deepcrag"));
        addPrefix("frostcrystal_prefix", "Frostcrystal ", "#A9CCE3", 2, new ThemeCustomisationDiscovery("Snowfell"));
        addPrefix("lumincryst_prefix", "Lumincryst ", "#F9E79F", 3, new ThemeCustomisationDiscovery("Deepcrag"));
        addPrefix("geode_prefix", "Geode ", "#BB8FCE", 2, new ThemeCustomisationDiscovery("Deepcrag"));
        addPrefix("prismal_prefix", "Prismal ", "#FAD7A0", 3, new ThemeCustomisationDiscovery("Deepcrag"));
        addPrefix("glimmered_prefix", "Glimmered ", "#EBDEF0", 2, new ThemeCustomisationDiscovery("Glimmergrove"));
        addPrefix("facet_prefix", "Facet ", "#AED6F1", 1, new ThemeCustomisationDiscovery("Deepcrag"));
        addPrefix("radiantcrystal_prefix", "Radiantcrystal ", "#FDEBD0", 3, new ThemeCustomisationDiscovery("Deepcrag"));
        addPrefix("starshard_prefix", "Starshard ", "#D2B4DE", 4,new ThemeCustomisationDiscovery("Space"));
        addPrefix("quartzforged_prefix", "Quartzforged ", "#F7F7F7", 3, new ThemeCustomisationDiscovery("Deepcrag"));
        addPrefix("amethystine_prefix", "Amethystine ", "#C39BD3", 3, new ThemeCustomisationDiscovery("Deepcrag"));
        addPrefix("opaline_prefix", "Opaline ", "#FDF1FF", 2, new ThemeCustomisationDiscovery("Deepcrag"));
        addPrefix("calcite_prefix", "Calcite ", "#FFF7D6", 1, new ThemeCustomisationDiscovery("Deepcrag"));
        addPrefix("ronin_prefix", "Ronin ", "#7F8C8D", 2, new VaultLevelDiscovery(65));
        addPrefix("kensai_prefix", "Kensai ", "#C0392B", 3, new VaultLevelDiscovery(65));
        addPrefix("shogun_prefix", "Shogun ", "#4A235A", 4, new VaultLevelDiscovery(65));
        addPrefix("bushido_prefix", "Bushido ", "#1F618D", 3, new VaultLevelDiscovery(65));
        addPrefix("oni_slayer_prefix", "Oni-Slayer ", "#922B21", 3, new VaultLevelDiscovery(85));
        addPrefix("windwalker_prefix", "Windwalker ", "#D5D8DC", 2, new VaultLevelDiscovery(77));
        addPrefix("moonblade_prefix", "Moonblade ", "#F2F4F4", 2, new VaultLevelDiscovery(66));
        addPrefix("yokai_bane_prefix", "Yokai-Bane ", "#7D3C98", 3, new VaultLevelDiscovery(55));
        addPrefix("jade_samurai_prefix", "Jade Samurai ", "#2ECC71", 2, new VaultLevelDiscovery(64));
        addPrefix("crimson_ronin_prefix", "Crimson Ronin ", "#A93226", 3, new VaultLevelDiscovery(89));
        addPrefix("shadow_katana_prefix", "Shadow Katana ", "#1B2631", 4, new VaultLevelDiscovery(97));
        addPrefix("storm_samurai_prefix", "Storm Samurai ", "#5DADE2", 3, new VaultLevelDiscovery(43));
        addPrefix("bladeshaper_prefix", "Bladeshaper ", "#99A3A4", 2, new VaultLevelDiscovery(99));
        addPrefix("dragoncrest_prefix", "Dragoncrest ", "#76448A", 3, new VaultLevelDiscovery(95));
        addPrefix("steel_tempest_prefix", "Steel Tempest ", "#B3B6B7", 2, new VaultLevelDiscovery(45));
        addPrefix("leafy_prefix", "Leafy", "#6B8E23", 3, new ThemeCustomisationDiscovery("Glimmergrove"));
        addPrefix("blooming_prefix", "Blooming ", "#98FB98", 2, new ThemeCustomisationDiscovery("Glimmergrove"));
        addPrefix("mossy_prefix", "Mossy ", "#556B2F", 2, new ThemeCustomisationDiscovery("Glimmergrove"));
        addPrefix("sunbeam_prefix", "Sunbeam ", "#FFD700", 2, new ThemeCustomisationDiscovery("Glimmergrove"));
        addPrefix("twiggy_prefix", "Twiggy ", "#8B4513", 2,new ThemeCustomisationDiscovery("Glimmergrove"));
        addPrefix("sprout_prefix", "Sprout ", "#7CFC00", 3,new ThemeCustomisationDiscovery("Glimmergrove"));
        addPrefix("petal_prefix", "Petal ", "#FFB6C1", 2,new ThemeCustomisationDiscovery("Glimmergrove"));
        addPrefix("acorn_prefix", "Acorn ", "#A0522D", 2, new ThemeCustomisationDiscovery("Harvest"));
        addPrefix("breezy_prefix", "Breezy ", "#87CEEB", 2,new VaultLevelDiscovery(15));
        addPrefix("fluffy_prefix", "Fluffy ", "#FFC0CB", 3, new ThemeCustomisationDiscovery("Candoria"));
        addPrefix("sparkly_prefix", "Sparkly ", "#FFD700", 2,new VaultLevelDiscovery(30));
        addPrefix("bubbly_prefix", "Bubbly ", "#87CEFA", 2, new ThemeCustomisationDiscovery("Candoria"));
        addPrefix("twinkle_prefix", "Twinkle ", "#FFFACD", 2,new VaultLevelDiscovery(35));
        addPrefix("cuddly_prefix", "Cuddly ", "#FFB6C1", 2, new ThemeCustomisationDiscovery("Candoria"));
        addPrefix("hoppy_prefix", "Hoppy ", "#98FB98", 2, new ThemeCustomisationDiscovery("Candoria"));
        addPrefix("cheery_prefix", "Cheery ", "#FFDAB9", 3, new ThemeCustomisationDiscovery("Candoria"));
        addPrefix("peppy_prefix", "Peppy ", "#FF69B4", 2, new ThemeCustomisationDiscovery("Candoria"));
        addPrefix("shiny_prefix", "Shiny ", "#FFFFE0", 2, new VaultLevelDiscovery(77));
        addPrefix("radiant_prefix", "Radiant ", "#FFD1DC", 3, new ThemeCustomisationDiscovery("Sandsworn"));
        addPrefix("luminous_prefix", "Luminous ", "#FFE4B5", 2, new ThemeCustomisationDiscovery("Sandsworn"));
        addPrefix("elegant_prefix", "Elegant ", "#E6E6FA", 2, new ThemeCustomisationDiscovery("Sporegrove"));
        addPrefix("glimmering_prefix", "Glimmering ", "#F0E68C", 2,new ThemeCustomisationDiscovery("Glimmergrove"));
        addPrefix("serene_prefix", "Serene ", "#AFEEEE", 2,new ThemeCustomisationDiscovery("Glimmergrove"));
        addPrefix("dazzling_prefix", "Dazzling ", "#FFFACD", 2,new VaultLevelDiscovery(85));
        addPrefix("silken_prefix", "Silken ", "#F5F5DC", 2, new ThemeCustomisationDiscovery("Sporegrove"));
        addPrefix("moonlit_prefix", "Moonlit ", "#E0FFFF", 2, new ThemeCustomisationDiscovery("Spooky"));


        addSuffix("first_flame_suffix", " of the First Flame", "#E74C3C", 2, new ArtifactCustomisationDiscovery(1));
        addSuffix("legends_suffix", " of Legends", "#3498DB", 2, new HeraldCustomisationDiscovery());
        addSuffix("ascension_suffix", " of Ascension", "#F39C12", 20, new ArtifactCustomisationDiscovery(10));
        addSuffix("void_suffix", " of the Void", "#5D7D7E", 2, new ThemeCustomisationDiscovery("Void"));
        addSuffix("dragonslayer_suffix", " the Dragonslayer", "#C0392B", 2, new HeraldCustomisationDiscovery());
        addSuffix("shieldbreaker_suffix", " the Shieldbreaker", "#7B7D7D", 2,new ThemeCustomisationDiscovery("Raid"));
        addSuffix("frostborn_suffix", " the Frostborn", "#85C1E9", 2, new ThemeCustomisationDiscovery("Snowfell"));
        addSuffix("reaper_suffix", " the Reaper", "#900C3F", 2,new ThemeCustomisationDiscovery("Spooky"));
        addSuffix("version_suffix", " v2.0", "#2ECCFA", 2, new VaultLevelDiscovery(100));
        addSuffix("the_everflame_suffix", " the Everflame", "#D35400", 3, new ThemeCustomisationDiscovery("Nether"));
        addSuffix("of_shattered_realms_suffix", " of Shattered Realms", "#AAB7B8", 3, new ArtifactCustomisationDiscovery(7));
        addSuffix("of_the_sunforge_suffix", " of the Sunforge", "#F4D03F", 4, new ThemeCustomisationDiscovery("Sandsworn"));
        addSuffix("the_starfaller_suffix", " the Starfaller", "#AED6F1", 2,new HeraldCustomisationDiscovery());
        addSuffix("of_the_voidheart_suffix", " of the Voidheart", "#1F618D", 3,new ThemeCustomisationDiscovery("Void"));
        addSuffix("the_runeweaver_suffix", " the Runeweaver", "#BB8FCE", 2,new ArtifactCustomisationDiscovery(12));
        addSuffix("the_blooddrinker_suffix", " the Blooddrinker", "#C0392B", 3, new ThemeCustomisationDiscovery("Bloodveil"));
        addSuffix("of_the_first_storm_suffix", " of the First Storm", "#5DADE2", 2, new ArtifactCustomisationDiscovery(1));
        addSuffix("the_unbroken_suffix", " the Unbroken", "#7DCEA0", 3, new ArtifactCustomisationDiscovery(13));
        addSuffix("of_arcane_echoes_suffix", " of Arcane Echoes", "#A569BD", 2, new ArtifactCustomisationDiscovery(17));
        addSuffix("the_dreadforge_suffix", " the Dreadforge", "#4A235A", 3, new VaultLevelDiscovery(90));
        addSuffix("of_the_eternal_night_suffix", " of the Eternal Night", "#1C1C1C", 4, new ThemeCustomisationDiscovery("Spooky"));
        addSuffix("the_vindicator_suffix", " the Vindicator", "#7F8C8D", 2, new ThemeCustomisationDiscovery("Raid"));
        addSuffix("the_soultaker_suffix", " the Soultaker", "#900C3F", 3,new ThemeCustomisationDiscovery("Sporegrove"));
        addSuffix("the_icebreaker_suffix", " the Icebreaker", "#85C1E9", 2,new ThemeCustomisationDiscovery("Snowfell"));
        addSuffix("of_the_twilight_suffix", " of the Twilight", "#76448A", 3,new ThemeCustomisationDiscovery("Sporegrove"));
        addSuffix("the_mirage_suffix", " the Mirage", "#FADBD8", 2, new ThemeCustomisationDiscovery("Sandsworn"));
        addSuffix("the_damned_suffix", " the Damned", "#5C1A1A", 3,new ThemeCustomisationDiscovery("Sporegrove"));
        addSuffix("the_fallen_suffix", " the Fallen", "#7B241C", 2,new ThemeCustomisationDiscovery("Sporegrove"));
        addSuffix("the_pitfiend_suffix", " the Pitfiend", "#8E1B1B", 3, new ThemeCustomisationDiscovery("Nether"));
        addSuffix("the_hellcaller_suffix", " the Hellcaller", "#A93226", 3, new ThemeCustomisationDiscovery("Nether"));
        addSuffix("the_soulflayer_suffix", " the Soulflayer", "#641E16", 2, new ThemeCustomisationDiscovery("Nether"));
        addSuffix("the_crimson_hunger_suffix", " the Crimson Hunger", "#922B21", 3, new ThemeCustomisationDiscovery("Nether"));
        addSuffix("the_bloodlord_suffix", " the Bloodlord", "#BB0A1E", 4, new ThemeCustomisationDiscovery("Bloodveil"));
        addSuffix("the_abyss_suffix", " the Abyss", "#2E0F0F", 2, new ThemeCustomisationDiscovery("LostDepths"));
        addSuffix("the_brimstone_suffix", " the Brimstone", "#E25822", 3, new ThemeCustomisationDiscovery("Nether"));
        addSuffix("the_hellstorm_suffix", " the Hellstorm", "#C0392B", 3, new ThemeCustomisationDiscovery("Nether"));
        addSuffix("the_dreadfire_suffix", " the Dreadfire", "#7B0000", 2, new ThemeCustomisationDiscovery("Nether"));
        addSuffix("the_shadowflame_suffix", " the Shadowflame", "#6C1E1E", 2, new ThemeCustomisationDiscovery("Spooky"));
        addSuffix("the_night_terror_suffix", " the Night Terror", "#4A0000", 3, new ThemeCustomisationDiscovery("Spooky"));
        addSuffix("the_sinweaver_suffix", " the Sinweaver", "#7D3C3C", 2, new ThemeCustomisationDiscovery("Spooky"));
        addSuffix("the_voideater_suffix", " the Voideater", "#3B0A0A", 2, new ThemeCustomisationDiscovery("Void"));
        addSuffix("of_the_seraph_suffix", " of the Seraph", "#F9EBEA", 3, new ThemeCustomisationDiscovery("Gods"));
        addSuffix("of_the_archangel_suffix", " of the Archangel", "#FDEBD0", 4,new ThemeCustomisationDiscovery("Gods"));
        addSuffix("of_divine_light_suffix", " of Divine Light", "#F7DC6F", 3,new ThemeCustomisationDiscovery("Gods"));
        addSuffix("of_the_sanctum_suffix", " of the Sanctum", "#EBF5FB", 2,new ThemeCustomisationDiscovery("Gods"));
        addSuffix("of_pure_grace_suffix", " of Pure Grace", "#F5EEF8", 2,new ThemeCustomisationDiscovery("Gods"));
        addSuffix("of_the_halo_suffix", " of the Halo", "#FFF9E3", 2,new ThemeCustomisationDiscovery("Gods"));
        addSuffix("of_the_dawnbringer_suffix", " of the Dawnbringer", "#FAF3C1", 3,new ThemeCustomisationDiscovery("Gods"));
        addSuffix("of_the_empyrion_suffix", " of the Empyrion", "#FDEDEC", 4,new ThemeCustomisationDiscovery("Gods"));
        addSuffix("of_the_radiant_host_suffix", " of the Radiant Host", "#F4ECF7", 3,new ThemeCustomisationDiscovery("Gods"));
        addSuffix("of_the_ascended_suffix", " of the Ascended", "#E8F8F5", 3,new HeraldCustomisationDiscovery());
        addSuffix("of_the_sunspire_suffix", " of the Sunspire", "#FFF2CC", 2,new ThemeCustomisationDiscovery("Sandsworn"));
        addSuffix("of_the_eternal_glow_suffix", " of the Eternal Glow", "#FEF9E7", 2,new HeraldCustomisationDiscovery());
        addSuffix("of_the_skyward_suffix", " of the Skyward", "#D6EAF8", 2,new ThemeCustomisationDiscovery("Aether"));
        addSuffix("of_the_celestium_suffix", " of the Celestium", "#EBDEF0", 3,new ThemeCustomisationDiscovery("Space"));
        addSuffix("of_the_lightbound_suffix", " of the Lightbound", "#F9E79F", 2,new ThemeCustomisationDiscovery("Sandsworn"));
        addSuffix("of_the_astral_plane_suffix", " of the Astral Plane", "#A569BD", 3, new ArtifactCustomisationDiscovery(20));
        addSuffix("of_the_cosmos_suffix", " of the Cosmos", "#7FB3D5", 3, new ArtifactCustomisationDiscovery(20));
        addSuffix("of_the_void_suffix", " of the Void", "#1C1C3C", 4, new ThemeCustomisationDiscovery("Void"));
        addSuffix("of_the_nebula_suffix", " of the Nebula", "#AF7AC5", 2, new ArtifactCustomisationDiscovery(20));
        addSuffix("of_the_galaxy_suffix", " of the Galaxy", "#5DADE2", 3, new ArtifactCustomisationDiscovery(20));
        addSuffix("of_the_event_horizon_suffix", " of the Event Horizon", "#0B0B0F", 4, new ArtifactCustomisationDiscovery(20));
        addSuffix("of_the_supercluster_suffix", " of the Supercluster", "#BB8FCE", 3, new ArtifactCustomisationDiscovery(20));
        addSuffix("of_the_dark_infinity_suffix", " of the Dark Infinity", "#0A0A16", 4, new ArtifactCustomisationDiscovery(20));
        addSuffix("of_the_quasar_suffix", " of the Quasar", "#7845FF", 3, new ArtifactCustomisationDiscovery(20));
        addSuffix("of_the_blackstar_suffix", " of the Blackstar", "#212F3D", 2, new ArtifactCustomisationDiscovery(20));
        addSuffix("of_the_starforge_suffix", " of the Starforge", "#566DF0", 3, new ArtifactCustomisationDiscovery(20));
        addSuffix("of_the_cosmic_wave_suffix", " of the Cosmic Wave", "#85929E", 2, new ArtifactCustomisationDiscovery(20));
        addSuffix("of_the_gravemind_suffix", " of the Gravemind", "#34495E", 3,new ThemeCustomisationDiscovery("Spooky"));
        addSuffix("of_the_chrono_depths_suffix", " of the Chrono Depths", "#AAB7B8", 2, new ArtifactCustomisationDiscovery(25));
        addSuffix("of_the_crimson_cutlass_suffix", " of the Crimson Cutlass", "#A93226", 3,new ThemeCustomisationDiscovery("Tropics"));
        addSuffix("of_the_tidecaller_suffix", " of the Tidecaller", "#1F618D", 2,new ThemeCustomisationDiscovery("Tropics"));
        addSuffix("of_the_black_flag_suffix", " of the Black Flag", "#0D0D0D", 4,new ThemeCustomisationDiscovery("Tropics"));
        addSuffix("of_the_kraken_suffix", " of the Kraken", "#1B2631", 3,new ThemeCustomisationDiscovery("Tropics"));
        addSuffix("of_the_high_seas_suffix", " of the High Seas", "#5DADE2", 2,new ThemeCustomisationDiscovery("Tropics"));
        addSuffix("of_the_bilge_rat_suffix", " of the Bilge Rat", "#7E5109", 1,new ThemeCustomisationDiscovery("Tropics"));
        addSuffix("of_the_greater_horizon_suffix", " of the Greater Horizon", "#85C1E9", 2, new ThemeCustomisationDiscovery("Sandsworn"));
        addSuffix("of_the_cursed_treasure_suffix", " of the Cursed Treasure", "#7D6608", 3, new ThemeCustomisationDiscovery("Tropics"));
        addSuffix("of_the_sea_reaver_suffix", " of the Sea-Reaver", "#34495E", 3,new ThemeCustomisationDiscovery("Tropics"));
        addSuffix("of_the_stormwake_suffix", " of the Stormwake", "#2C3E50", 2,new ThemeCustomisationDiscovery("Tropics"));
        addSuffix("of_the_sunken_king_suffix", " of the Sunken King", "#1C2833", 4,new ThemeCustomisationDiscovery("Tropics"));
        addSuffix("of_the_gallows_suffix", " of the Gallows", "#4A3728", 2,new ThemeCustomisationDiscovery("Tropics"));
        addSuffix("of_the_brine_depths_suffix", " of the Brine Depths", "#154360", 2, new ThemeCustomisationDiscovery("Underwater"));
        addSuffix("of_the_rusty_hook_suffix", " of the Rusty Hook", "#A97142", 1,new ThemeCustomisationDiscovery("Tropics"));
        addSuffix("of_the_tidebreaker_suffix", " of the Tidebreaker", "#21618C", 3,new ThemeCustomisationDiscovery("Tropics"));
        addSuffix("of_the_crystalspire_suffix", " of the Crystalspire", "#AEE5F8", 3,new ThemeCustomisationDiscovery("Deepcrag"));
        addSuffix("of_the_shatterpeak_suffix", " of the Shatterpeak", "#8FD3E8", 3, new ThemeCustomisationDiscovery("Snowfell"));
        addSuffix("of_the_primordial_gem_suffix", " of the Primordial Gem", "#D7BDE2", 4,new ThemeCustomisationDiscovery("Deepcrag"));
        addSuffix("of_the_frostshard_suffix", " of the Frostshard", "#A9CCE3", 2, new ThemeCustomisationDiscovery("Snowfell"));
        addSuffix("of_the_prismatic_depths_suffix", " of the Prismatic Depths", "#FAD7A0", 3,new ThemeCustomisationDiscovery("Deepcrag"));
        addSuffix("of_the_opal_vein_suffix", " of the Opal Vein", "#FDF1FF", 2,new ThemeCustomisationDiscovery("Deepcrag"));
        addSuffix("of_the_starcrystal_suffix", " of the Starcrystal", "#D2B4DE", 4, new ArtifactCustomisationDiscovery(20));
        addSuffix("of_the_glimmervault_suffix", " of the Glimmervault", "#EBDEF0", 2, new ThemeCustomisationDiscovery("Glimmergrove"));
        addSuffix("of_the_quartzwake_suffix", " of the Quartzwake", "#F7F7F7", 2,new ThemeCustomisationDiscovery("Deepcrag"));
        addSuffix("of_the_crystal_depths_suffix", " of the Crystal Depths", "#AED6F1", 3,new ThemeCustomisationDiscovery("Deepcrag"));
        addSuffix("of_the_lumengorge_suffix", " of the Lumengorge", "#FDEBD0", 3,new ThemeCustomisationDiscovery("Deepcrag"));
        addSuffix("of_the_faceted_star_suffix", " of the Faceted Star", "#C39BD3", 3,new ThemeCustomisationDiscovery("Space"));
        addSuffix("of_the_gemforge_suffix", " of the Gemforge", "#BB8FCE", 2,new ThemeCustomisationDiscovery("Deepcrag"));
        addSuffix("of_the_radiant_shard_suffix", " of the Radiant Shard", "#F9E79F", 2,new ArtifactCustomisationDiscovery(14));
        addSuffix("of_the_crystal_maw_suffix", " of the Crystal Maw", "#8E44AD", 4,new ThemeCustomisationDiscovery("Deepcrag"));
        addSuffix("of_the_ronin_path_suffix", " of the Ronin Path", "#7F8C8D", 2,new VaultLevelDiscovery(65));
        addSuffix("of_the_katana_suffix", " of the Katana", "#F2F4F4", 2, new VaultLevelDiscovery(65));
        addSuffix("of_the_crimson_shogun_suffix", " of the Crimson Shogun", "#A93226", 4,new VaultLevelDiscovery(65));
        addSuffix("of_the_wind_stance_suffix", " of the Wind Stance", "#D5D8DC", 2,new VaultLevelDiscovery(65));
        addSuffix("of_the_dragonblade_suffix", " of the Dragonblade", "#76448A", 3,new VaultLevelDiscovery(65));
        addSuffix("of_the_bushido_code_suffix", " of the Bushido Code", "#1F618D", 3,new VaultLevelDiscovery(65));
        addSuffix("of_the_oni_hunter_suffix", " of the Oni Hunter", "#922B21", 3);
        addSuffix("of_the_moonlit_edge_suffix", " of the Moonlit Edge", "#F2F4F4", 2,new ThemeCustomisationDiscovery("Sporegrove"));
        addSuffix("of_the_sakura_fall_suffix", " of the Sakura Fall", "#F5B7B1", 2,new ThemeCustomisationDiscovery("Sporegrove"));
        addSuffix("of_the_thunder_cut_suffix", " of the Thunder-Cut", "#5DADE2", 3,new VaultLevelDiscovery(65));
        addSuffix("of_the_silent_blade_suffix", " of the Silent Blade", "#1B2631", 4,new VaultLevelDiscovery(65));
        addSuffix("of_the_spirit_samurai_suffix", " of the Spirit Samurai", "#A9CCE3", 2,new VaultLevelDiscovery(65));
        addSuffix("of_the_dragon_crest_suffix", " of the Dragon Crest", "#7D3C98", 3,new VaultLevelDiscovery(65));
        addSuffix("of_the_steel_tempest_suffix", " of the Steel Tempest", "#B3B6B7", 2,new VaultLevelDiscovery(65));
        addSuffix("of_the_yokai_watcher_suffix", " of the Yokai Watcher", "#7D3C98", 2,new VaultLevelDiscovery(65));
        addSuffix("of_the_grove_suffix", " of the Grove", "#32CD32", 3, new ThemeCustomisationDiscovery("Sporegrove"));
        addSuffix("of_sunny_days_suffix", " of Sunny Days", "#FFD700", 2, new ThemeCustomisationDiscovery("Sandsworn"));
        addSuffix("of_whispering_leaves_suffix", " of Whispering Leaves", "#228B22", 2,new ThemeCustomisationDiscovery("Sporegrove"));
        addSuffix("of_blossoms_suffix", " of Blossoms", "#FF69B4", 2,new ThemeCustomisationDiscovery("Sporegrove"));
        addSuffix("of_forest_friends_suffix", " of Forest Friends", "#6B8E23", 2,new ThemeCustomisationDiscovery("Sporegrove"));
        addSuffix("of_moonlit_paths_suffix", " of Moonlit Paths", "#E0FFFF", 2,new ThemeCustomisationDiscovery("Sporegrove"));
        addSuffix("of_acorn_luck_suffix", " of Acorn Luck", "#A0522D", 2,new ThemeCustomisationDiscovery("Sporegrove"));
        addSuffix("of_squirrels_suffix", " of Squirrels", "#D2B48C", 1,new ThemeCustomisationDiscovery("Sporegrove"));
        addSuffix("of_snuggles_suffix", " of Snuggles", "#FFB6C1", 3,new ThemeCustomisationDiscovery("Candoria"));
        addSuffix("of_rainbows_suffix", " of Rainbows", "#FFD700", 2,new ThemeCustomisationDiscovery("Candoria"));
        addSuffix("of_sparkles_suffix", " of Sparkles", "#FFFACD", 2,new ThemeCustomisationDiscovery("Candoria"));
        addSuffix("of_purrs_suffix", " of Purrs", "#FFE4E1", 2,new ThemeCustomisationDiscovery("Candoria"));
        addSuffix("of_bouncing_suffix", " of Bouncing", "#98FB98", 2,new ThemeCustomisationDiscovery("Candoria"));
        addSuffix("of_giggles_suffix", " of Giggles", "#FFDAB9", 2,new ThemeCustomisationDiscovery("Candoria"));
        addSuffix("of_hugs_suffix", " of Hugs", "#FF69B4", 2,new ThemeCustomisationDiscovery("Candoria"));
        addSuffix("of_twinkling_suffix", " of Twinkling", "#E6E6FA", 2,new ThemeCustomisationDiscovery("Candoria"));
        addSuffix("of_cupcakes_suffix", " of Cupcakes", "#FFF0F5", 2,new ThemeCustomisationDiscovery("Candoria"));
        addSuffix("of_blossoms_suffix", " of Blossoms", "#FFC0CB", 3, new ThemeCustomisationDiscovery("Sporegrove"));
        addSuffix("of_starlight_suffix", " of Starlight", "#F0FFFF", 2, new ThemeCustomisationDiscovery("Sporegrove"));
        addSuffix("of_moonlight_suffix", " of Moonlight", "#E0FFFF", 2,new ThemeCustomisationDiscovery("Sporegrove"));
        addSuffix("of_sunrise_suffix", " of Sunrise", "#FFDAB9", 2, new ThemeCustomisationDiscovery("Sandsworn"));
        addSuffix("of_aurora_suffix", " of Aurora", "#AFEEEE", 2);
        addSuffix("of_dreams_suffix", " of Dreams", "#FFE4E1", 2, new ThemeCustomisationDiscovery("Plastic"));
        addSuffix("of_glory_suffix", " of Glory", "#FFFACD", 2, new ArtifactCustomisationDiscovery(12));
        addSuffix("of_sparkle_suffix", " of Sparkle", "#F5F5DC", 2);
        addSuffix("of_elegance_suffix", " of Elegance", "#E6E6FA", 2, new ThemeCustomisationDiscovery("Sporegrove"));
        addSuffix("of_gleaming_suffix", " of Gleaming", "#FFF8DC", 2,new ThemeCustomisationDiscovery("Glimmergrove"));

        //Challenge unlocks
        addPrefix("cat_eyed_prefix", "Cat-Eyed", "#9EA637", 2, new GreedChallengeDiscovery("pitch_black"));
        addSuffix("of_the_inky_black_suffix", "of the Inky Black", "#03020E", 2, new GreedChallengeDiscovery("pitch_black"));

        addPrefix("champion_prefix", "Champion", "#B47410", 2, new GreedChallengeDiscovery("ultra_hard"));
        addPrefix("sweaty_prefix", "Sweaty", "#B44710", 2, new GreedChallengeDiscovery("ultra_hard"));
        addSuffix("the_sweat_suffix", "the Sweat", "#B44710", 2, new GreedChallengeDiscovery("ultra_hard"));
        addSuffix("the_challenger_suffix", "the Challenger", "#B4473A", 2, new GreedChallengeDiscovery("ultra_hard"));

        addPrefix("enchanted_prefix", "Enchanted", "#B447AC", 2, new GreedChallengeDiscovery("elixir_of_doom"));
        addSuffix("of_elixir", "of Elixir", "#03020E", 2, new GreedChallengeDiscovery("elixir_of_doom"));
        addPrefix("elixir_lover_prefix", "Elixir Lover", "#03020E", 2, new GreedChallengeDiscovery("elixir_of_doom"));

        addPrefix("ballistic_prefix", "Ballistic", "#230094", 2, new GreedChallengeDiscovery("ballistic_bingo_blackout"));

        addPrefix("collector_prefix", "Collector", "#23A594", 2, new GreedChallengeDiscovery("blackout_scavingo"));

        addPrefix("regent_prefix", "Regent", "#D5A500", 2, new GreedChallengeDiscovery("gods_challenge"));
        addPrefix("proven_prefix", "Proven", "#D5A500", 2, new GreedChallengeDiscovery("gods_challenge"));
        addSuffix("of_velara_suffix", "of Velara", "#00A500", 2, new GreedChallengeDiscovery("gods_challenge"));
        addSuffix("of_wendarr_suffix", "of Wendarr", "#D5A500", 2, new GreedChallengeDiscovery("gods_challenge"));
        addSuffix("of_tenos_suffix", "of Tenos", "#00BAC8", 2, new GreedChallengeDiscovery("gods_challenge"));
        addSuffix("of_idona_suffix", "of Idona", "#B60000", 2, new GreedChallengeDiscovery("gods_challenge"));

        addPrefix("alchemist_prefix", "Alchemist", "#23A594", 2, new GreedChallengeDiscovery("big_bad_brew"));
        addSuffix("troubling_suffix", "the Troubling", "#B67E59", 2, new GreedChallengeDiscovery("big_bad_brew"));

        addPrefix("insane_prefix", "Insane", "#B67EA1", 2, new GreedChallengeDiscovery("chaos_chaos_chaos"));

        addPrefix("raging_prefix", "Raging", "#B63025", 2, new GreedChallengeDiscovery("rage_cage"));

        addPrefix("survivor_prefix", "Survivor", "#007925", 2, new GreedChallengeDiscovery("survival_of_the_fittest"));

    }
}
