package xyz.iwolfking.woldsvaults.init;

import iskallia.vault.VaultMod;
import net.minecraft.ChatFormatting;
import net.minecraft.network.chat.TextColor;
import net.minecraft.network.chat.TextComponent;
import net.minecraft.network.chat.TranslatableComponent;
import net.minecraft.sounds.SoundEvents;
import net.minecraft.sounds.SoundSource;
import net.minecraft.world.effect.MobEffects;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.level.Explosion;
import net.minecraft.world.level.block.Blocks;
import xyz.iwolfking.woldsvaults.WoldsVaults;
import xyz.iwolfking.woldsvaults.api.core.vault_events.VaultEventSystem;
import xyz.iwolfking.woldsvaults.api.core.vault_events.impl.tasks.*;
import xyz.iwolfking.woldsvaults.api.core.vault_events.impl.tasks.survival.SurvivalWaveAdjustmentTask;
import xyz.iwolfking.woldsvaults.api.core.vault_events.lib.EventTag;
import xyz.iwolfking.woldsvaults.api.core.vault_events.VaultEvent;
import xyz.iwolfking.woldsvaults.api.util.ref.Effect;

import java.util.List;

public class ModVaultEvents {

    public static void init() {
        VaultEventSystem.register(WoldsVaults.id("xp_boost"), new VaultEvent.Builder()
                .tag(EventTag.POSITIVE)
                .tag(EventTag.ADDS_MODIFIER)
                .message(new TextComponent("Increased §eVault Experience§r gain by 20%!"))
                .displayType(VaultEvent.EventDisplayType.CHAT_MESSAGE_ALL)
                .color(TextColor.fromLegacyFormat(ChatFormatting.GOLD))
                .task(new VaultModifierTask(VaultMod.id("xp_gain"), 1))
                .build("XP Boost", new TextComponent("Gain 20% more Vault Experience!")));
        VaultEventSystem.register(WoldsVaults.id("survival_restore"), new VaultEvent.Builder()
                .tag(EventTag.POSITIVE)
                .tag(EventTag.ADDS_MODIFIER)
                .message(new TextComponent("You feel a wave of restoration wash over you!"))
                .displayType(VaultEvent.EventDisplayType.CHAT_MESSAGE_ALL)
                .color(TextColor.fromLegacyFormat(ChatFormatting.GOLD))
                .task(new VaultModifierTask(VaultMod.id("ultimate_regeneration"), 1, 900))
                .build("Ultimate Regeneration", new TextComponent("Grants Ultimate Regeneration for 45 seconds!")));
        VaultEventSystem.register(WoldsVaults.id("loot_boost"), new VaultEvent.Builder()
                .tag(EventTag.POSITIVE)
                .tag(EventTag.ADDS_MODIFIER)
                .message(new TextComponent("§6Loot Boost§r! Catalyst Fragment Chance, Item Quantity, Item Rarity and Soul Shard Chance increased!"))
                .displayType(VaultEvent.EventDisplayType.CHAT_MESSAGE_ALL)
                .color(TextColor.fromLegacyFormat(ChatFormatting.GOLD))
                .task(new VaultModifierTask(VaultMod.id("sparkling"), 1))
                .task(new VaultModifierTask(VaultMod.id("item_quantity2"), 1))
                .task(new VaultModifierTask(VaultMod.id("pristine"), 1))
                .task(new VaultModifierTask(VaultMod.id("soul_boost"), 1))
                .build("Loot Boost", new TextComponent("Increase catalyst fragment chance, item quantity, item rarity, and soul shard chance!")));
        VaultEventSystem.register(WoldsVaults.id("artifact_boost"), new VaultEvent.Builder()
                .tag(EventTag.POSITIVE)
                .tag(EventTag.ADDS_MODIFIER)
                .message(new TextComponent("You feel your chance at an §eArtifact§r in your §6Reward Crate§r grow!"))
                .displayType(VaultEvent.EventDisplayType.CHAT_MESSAGE_ALL)
                .color(TextColor.fromLegacyFormat(ChatFormatting.GOLD))
                .task(new VaultModifierTask(VaultMod.id("serendipitous"), 1))
                .build("Artifact Boost", new TextComponent("Increases chance for an Artifact this Vault!")));
        VaultEventSystem.register(WoldsVaults.id("gear_cache"), new VaultEvent.Builder()
                .tag(EventTag.POSITIVE)
                .message(new TextComponent("You feel your §6Reward Crate§r grow heavier with §4eVault Gear§r!"))
                .displayType(VaultEvent.EventDisplayType.CHAT_MESSAGE_ALL)
                .color(TextColor.fromLegacyFormat(ChatFormatting.GOLD))
                .task(new AddCrateItemTask(VaultMod.id("survival_gear_cache")))
                .build("Fruit Cache", new TextComponent("Adds Fruit to your Vault Crate!")));
        VaultEventSystem.register(WoldsVaults.id("fruit_cache"), new VaultEvent.Builder()
                .tag(EventTag.POSITIVE)
                .message(new TextComponent("You feel your §6Reward Crate§r grow heavier with §4Fruit§r!"))
                .displayType(VaultEvent.EventDisplayType.CHAT_MESSAGE_ALL)
                .color(TextColor.fromLegacyFormat(ChatFormatting.GOLD))
                .task(new AddCrateItemTask(VaultMod.id("dragon_goblin/fruit")))
                .build("Fruit Cache", new TextComponent("Adds Fruit to your Vault Crate!")));
        VaultEventSystem.register(WoldsVaults.id("treasure_cache"), new VaultEvent.Builder()
                .tag(EventTag.POSITIVE)
                .message(new TextComponent("You feel your §6Reward Crate§r grow heavier with §6Treasure Loot§r!"))
                .displayType(VaultEvent.EventDisplayType.CHAT_MESSAGE_ALL)
                .color(TextColor.fromLegacyFormat(ChatFormatting.GOLD))
                .task(new RepeatTask(LeveledTask.of(taskMap -> {
                    taskMap.put(0, new AddCrateItemTask(VaultMod.id("treasure_sand_lvl0")));
                    taskMap.put(50, new AddCrateItemTask(VaultMod.id("treasure_chest_stand_lvl50")));
                }), 0, 2))
                .build("Champion Cache", new TextComponent("Adds 3 Champion Loot items to your Vault Crate!")));
        VaultEventSystem.register(WoldsVaults.id("champion_cache"), new VaultEvent.Builder()
                .tag(EventTag.POSITIVE)
                .message(new TextComponent("You feel your §6Reward Crate§r grow heavier with §3Champion Loot§r!"))
                .displayType(VaultEvent.EventDisplayType.CHAT_MESSAGE_ALL)
                .color(TextColor.fromLegacyFormat(ChatFormatting.GOLD))
                        .task(new RepeatTask(LeveledTask.of(taskMap -> {
                            taskMap.put(0, new AddCrateItemTask(VaultMod.id("champion_loot_lvl0")));
                            taskMap.put(20, new AddCrateItemTask(VaultMod.id("champion_loot_lvl20")));
                            taskMap.put(50, new AddCrateItemTask(VaultMod.id("champion_loot_lvl50")));
                        }), 0, 3))
                .build("Champion Cache", new TextComponent("Adds 3 Champion Loot items to your Vault Crate!")));
        VaultEventSystem.register(WoldsVaults.id("trinket_cache"), new VaultEvent.Builder()
                .tag(EventTag.POSITIVE)
                .message(new TextComponent("You feel your §6Reward Crate§r grow heavier with a shiny §dTrinket§r!"))
                .displayType(VaultEvent.EventDisplayType.CHAT_MESSAGE_ALL)
                .color(TextColor.fromLegacyFormat(ChatFormatting.GOLD))
                .task(new AddCrateItemTask(VaultMod.id("royale_loot_trinket")))
                .build("Trinkets and Baubles", new TextComponent("Adds a Trinket to your Vault Crate!")));
        VaultEventSystem.register(WoldsVaults.id("crate_tier"), new VaultEvent.Builder()
                .tag(EventTag.POSITIVE)
                .tag(EventTag.ADDS_MODIFIER)
                .message((TextComponent) new TextComponent("Congrats on your survival so far! 1x").append(new TextComponent("Crate Tier").withStyle(ChatFormatting.AQUA)).append(" was added to the vault!"))
                .displayType(VaultEvent.EventDisplayType.NONE)
                .color(TextColor.fromLegacyFormat(ChatFormatting.GOLD))
                .task(new VaultModifierTask(VaultMod.id("crate_tier"), 1))
                .build("Crate Tier", new TextComponent("Adds a crate tier to the vault.")));
        VaultEventSystem.register(WoldsVaults.id("survival_mob_crit"), new VaultEvent.Builder()
                .tag(EventTag.NEGATIVE)
                .tag(EventTag.ADDS_MODIFIER)
                .message(new TextComponent("The mobs become more §6critical§r of you."))
                .displayType(VaultEvent.EventDisplayType.CHAT_MESSAGE_ALL)
                .color(TextColor.fromLegacyFormat(ChatFormatting.GOLD))
                .task(new VaultModifierTask(VaultMod.id("critical_mobs"), 1))
                .build("Survival Mob Crit", new TextComponent("Increases mob critical strike chance.")));
        VaultEventSystem.register(WoldsVaults.id("survival_mob_onhits"), new VaultEvent.Builder()
                .tag(EventTag.NEGATIVE)
                .tag(EventTag.ADDS_MODIFIER)
                .message(new TextComponent("Chemicals stir in the air..."))
                .displayType(VaultEvent.EventDisplayType.CHAT_MESSAGE_ALL)
                .color(TextColor.fromLegacyFormat(ChatFormatting.GOLD))
                .task(new VaultModifierFromPoolTask(VaultMod.id("mob_onhits")))
                .build("Survival Mob On-Hits", new TextComponent("Adds a random effect on hit modifier to mobs.")));
        VaultEventSystem.register(WoldsVaults.id("survival_mob_buff"), new VaultEvent.Builder()
                .tag(EventTag.NEGATIVE)
                .tag(EventTag.ADDS_MODIFIER)
                .message(new TextComponent("You feel the mobs get stronger..."))
                .displayType(VaultEvent.EventDisplayType.CHAT_MESSAGE_ALL)
                .color(TextColor.fromLegacyFormat(ChatFormatting.GOLD))
                .task(new VaultModifierTask(VaultMod.id("challenge_stack"), 1))
                .build("Survival Mob Buff", new TextComponent("Makes mobs healthier, hit harder, and move faster.")));
        VaultEventSystem.register(WoldsVaults.id("survival_mob_effect"), new VaultEvent.Builder()
                .tag(EventTag.NEGATIVE)
                .tag(EventTag.ADDS_MODIFIER)
                .message(new TextComponent("You feel the mobs augment their abilities..."))
                .displayType(VaultEvent.EventDisplayType.CHAT_MESSAGE_ALL)
                .color(TextColor.fromLegacyFormat(ChatFormatting.GOLD))
                .task(new WeightedTask.Builder()
                        .task(new VaultModifierTask(WoldsVaults.id("regenerating_mobs"), 1), 1)
                        .task(new VaultModifierTask(WoldsVaults.id("resistant_mobs"), 1), 4)
                        .task(new VaultModifierTask(WoldsVaults.id("phantasmal_mobs"), 1), 2)
                        .task(new VaultModifierTask(WoldsVaults.id("fleet_footed_mobs"), 1), 4)
                        .build()
                )
                .build("Survival Mob Effect", new TextComponent("Adds a random Mob Effect modifier to the Vault.")));
        VaultEventSystem.register(WoldsVaults.id("survival_player_nerf"), new VaultEvent.Builder()
                .tag(EventTag.NEGATIVE)
                .tag(EventTag.ADDS_MODIFIER)
                .message(new TextComponent("You feel yourself get weaker... cooldown reduction, resistance, healing effectiveness, and mana regeneration decreased..."))
                .displayType(VaultEvent.EventDisplayType.CHAT_MESSAGE_ALL)
                .color(TextColor.fromLegacyFormat(ChatFormatting.GOLD))
                .task(new VaultModifierTask(VaultMod.id("inert"), 1))
                .task(new VaultModifierTask(VaultMod.id("vulnerable"), 1))
                .task(new VaultModifierTask(VaultMod.id("antiheal"), 1))
                .task(new VaultModifierTask(VaultMod.id("draining"), 1))
                .build("Survival Nerf", new TextComponent("Decreases your mana regen, cooldown reduction, resistance, and healing effectiveness.")));
        VaultEventSystem.register(WoldsVaults.id("survival_wave_decrease"), new VaultEvent.Builder()
                .tag(EventTag.SURVIVAL)
                .tag(EventTag.EXTRA_LONG_COOLDOWN)
                .message(new TextComponent("The tier of §2Survival§r mob spawns has been lowered!"))
                .displayType(VaultEvent.EventDisplayType.CHAT_MESSAGE_ALL)
                .color(TextColor.fromLegacyFormat(ChatFormatting.GREEN))
                .task(new SurvivalWaveAdjustmentTask(-1))
                .task(new AddVaultTimeTask(-1200))
                .build("Time Trade - Decrease", new TextComponent("Lowers the tier of §2Survival§r mob spawns by 1, removes a minute from the Vault Timer")));
        VaultEventSystem.register(WoldsVaults.id("survival_wave_increase"), new VaultEvent.Builder()
                .tag(EventTag.SURVIVAL)
                .tag(EventTag.LONG_COOLDOWN)
                .message(new TextComponent("The tier of §2Survival§r mob spawns has been increased!"))
                .displayType(VaultEvent.EventDisplayType.CHAT_MESSAGE_ALL)
                .color(TextColor.fromLegacyFormat(ChatFormatting.GREEN))
                .task(new SurvivalWaveAdjustmentTask(1))
                .task(new AddVaultTimeTask(1200))
                .build("Time Trade - Increase", new TextComponent("Increases the tier of §2Survival§r mob spawns by 1, adds a minute to the Vault Timer")));
        VaultEventSystem.register(WoldsVaults.id("survival_time_increase"), new VaultEvent.Builder()
                .tag(EventTag.SURVIVAL)
                .tag(EventTag.LONG_COOLDOWN)
                .message(new TextComponent("30 seconds was added to the Vault Timer!"))
                .displayType(VaultEvent.EventDisplayType.CHAT_MESSAGE_ALL)
                .color(TextColor.fromLegacyFormat(ChatFormatting.GREEN))
                .task(new AddVaultTimeTask(600))
                .build("Timer Bump", new TextComponent("Adds 30 seconds to the Vault Timer.")));
        VaultEventSystem.register(WoldsVaults.id("survival_resistance"), new VaultEvent.Builder()
                .tag(EventTag.SURVIVAL)
                .tag(EventTag.SHORT_COOLDOWN)
                .displayType(VaultEvent.EventDisplayType.NONE)
                .color(TextColor.fromLegacyFormat(ChatFormatting.GREEN))
                .task(new PlayerMobEffectTask(List.of(new Effect(MobEffects.DAMAGE_RESISTANCE, 4, 600), new Effect(MobEffects.REGENERATION, 1, 600))))
                .build("Recovery", new TextComponent("Gives you Resistance 5 and Regeneration 2 for 30 seconds.")));
        VaultEventSystem.register(WoldsVaults.id("survival_lunar"), new VaultEvent.Builder()
                .tag(EventTag.SURVIVAL)
                .message(new TextComponent("Activated Lunar gravity for mobs!"))
                .displayType(VaultEvent.EventDisplayType.CHAT_MESSAGE_ALL)
                .color(TextColor.fromLegacyFormat(ChatFormatting.GREEN))
                .task(new VaultModifierTask(VaultMod.id("lunar"), 1, 900))
                .build("Respite", new TextComponent("Sends mobs to the sky for a while!")));
        VaultEventSystem.register(WoldsVaults.id("survival_loot_beacon"), new VaultEvent.Builder()
                .tag(EventTag.SURVIVAL)
                .tag(EventTag.LONG_COOLDOWN)
                .message(new TextComponent("Item Quantity and Rarity increased, Mob Health, Damage, and Speed increased!"))
                .displayType(VaultEvent.EventDisplayType.CHAT_MESSAGE_ALL)
                .color(TextColor.fromLegacyFormat(ChatFormatting.GREEN))
                        .task(new VaultModifierTask(VaultMod.id("item_quantity2"), 1))
                        .task(new VaultModifierTask(VaultMod.id("pristine"), 1))
                        .task(new VaultModifierTask(VaultMod.id("challenge_stack"), 2))
                .build("Loot Beacon", new TextComponent("Increases Item Quantity and Item Rarity, Increases Mob health, damage, and speed.")));
        VaultEventSystem.register(WoldsVaults.id("midas_beacon"), new VaultEvent.Builder()
                .tag(EventTag.SURVIVAL)
                .tag(EventTag.EXTRA_LONG_COOLDOWN)
                .message(new TextComponent("Coins are exploding out of mobs for a brief period!"))
                .displayType(VaultEvent.EventDisplayType.CHAT_MESSAGE_ALL)
                .color(TextColor.fromLegacyFormat(ChatFormatting.GREEN))
                .task(new VaultModifierTask(VaultMod.id("bronze_nuke"), 1, 600))
                .task(new VaultModifierTask(VaultMod.id("fading"), 1, 600))
                .build("Midas Beacon", new TextComponent("Activates Coin Explosion and Fading for 30 seconds!")));
        VaultEventSystem.register(WoldsVaults.id("nova_beacon"), new VaultEvent.Builder()
                .tag(EventTag.SURVIVAL)
                .tag(EventTag.LONG_COOLDOWN)
                .message(new TextComponent("Mobs explode into Novas for a while!"))
                .displayType(VaultEvent.EventDisplayType.CHAT_MESSAGE_ALL)
                .color(TextColor.fromLegacyFormat(ChatFormatting.LIGHT_PURPLE))
                .task(new VaultModifierTask(VaultMod.id("kill_nova"), 1, 900))
                .build("Nova Beacon", new TextComponent("Activates Nova Explosion for 45 seconds!")));
        VaultEventSystem.register(WoldsVaults.id("frost_nova_beacon"), new VaultEvent.Builder()
                .tag(EventTag.SURVIVAL)
                .tag(EventTag.LONG_COOLDOWN)
                .message(new TextComponent("Mobs explode into Frost Novas for a while!"))
                .displayType(VaultEvent.EventDisplayType.CHAT_MESSAGE_ALL)
                .color(TextColor.fromLegacyFormat(ChatFormatting.LIGHT_PURPLE))
                .task(new VaultModifierTask(VaultMod.id("kill_frostnova"), 1, 900))
                .build("Frost Nova Beacon", new TextComponent("Activates Nova Explosion for 45 seconds!")));
        VaultEventSystem.register(WoldsVaults.id("glued_mobs"), new VaultEvent.Builder()
                .tag(EventTag.SURVIVAL)
                .tag(EventTag.LONG_COOLDOWN)
                .message(new TextComponent("Mobs are glued into place for a while!"))
                .displayType(VaultEvent.EventDisplayType.CHAT_MESSAGE_ALL)
                .color(TextColor.fromLegacyFormat(ChatFormatting.AQUA))
                .task(new VaultModifierTask(VaultMod.id("glued_mobs"), 1, 900))
                .build("Glue Beacon", new TextComponent("Activates Glued Mobs for 45 seconds!")));
        VaultEventSystem.register(WoldsVaults.id("nerf_beacon"), new VaultEvent.Builder()
                .tag(EventTag.SURVIVAL)
                .tag(EventTag.EXTRA_LONG_COOLDOWN)
                .message(new TextComponent("Mobs are made easier but loot is sad :("))
                .displayType(VaultEvent.EventDisplayType.CHAT_MESSAGE_ALL)
                .color(TextColor.fromLegacyFormat(ChatFormatting.YELLOW))
                .task(new VaultModifierTask(VaultMod.id("unlucky"), 1))
                .task(new VaultModifierTask(VaultMod.id("poor"), 1))
                .task(new VaultModifierTask(VaultMod.id("unchallenge_stack"), 1))
                .build("Nerf Beacon", new TextComponent("Item Quantity and Item Rarity reduced, mobs are made easier!")));
        VaultEventSystem.register(WoldsVaults.id("fruit_beacon"), new VaultEvent.Builder()
                .tag(EventTag.SURVIVAL)
                .tag(EventTag.SHORT_COOLDOWN)
                .message(new TextComponent("Player health has been reduced in return for some added time!"))
                .displayType(VaultEvent.EventDisplayType.CHAT_MESSAGE_ALL)
                .color(TextColor.fromLegacyFormat(ChatFormatting.RED))
                .task(new AddVaultTimeTask(900))
                .task(new VaultModifierTask(VaultMod.id("fading"), 1, 600))
                .task(new VaultModifierTask(VaultMod.id("injured_percent"), 1))
                .build("Fruit Beacon", new TextComponent("Adds 45 seconds but removes 10% of all player's health.")));
        VaultEventSystem.register(WoldsVaults.id("phoenix_beacon"), new VaultEvent.Builder()
                .tag(EventTag.SURVIVAL)
                .tag(EventTag.INFINITE_COOLDOWN)
                .message(new TextComponent("All players gain one revive, mobs are harder from here on out!"))
                .displayType(VaultEvent.EventDisplayType.CHAT_MESSAGE_ALL)
                .color(TextColor.fromLegacyFormat(ChatFormatting.DARK_RED))
                .task(new VaultModifierTask(VaultMod.id("phoenix"), 1))
                .task(new VaultModifierTask(VaultMod.id("challenge_stack"), 4))
                .build("Phoenix Beacon", new TextComponent("Adds a Phoenix stack to the Vault, adds 4 Challenge Stacks.")));
        VaultEventSystem.register(WoldsVaults.id("artifact_beacon"), new VaultEvent.Builder()
                .tag(EventTag.SURVIVAL)
                .tag(EventTag.SUPER_LONG_COOLDOWN)
                .message(new TextComponent("Artifact chance slightly increased!"))
                .displayType(VaultEvent.EventDisplayType.CHAT_MESSAGE_ALL)
                .color(TextColor.fromLegacyFormat(ChatFormatting.GOLD))
                .task(new VaultModifierTask(VaultMod.id("pogging"), 1))
                .task(new VaultModifierTask(VaultMod.id("challenge_stack"), 1))
                .build("Ancient Beacon", new TextComponent("Increases Artifact Chance slightly, makes mobs slightly harder.")));
        VaultEventSystem.register(WoldsVaults.id("tombstone_event"), new VaultEvent.Builder()
                .tag(EventTag.TOMBSTONE)
                .displayType(VaultEvent.EventDisplayType.NONE)
                        .task(new WeightedTask.Builder()
                                .task(new TaskGroup.Builder()
                                        .task(new SpawnMobTask.Builder()
                                            .entity(iskallia.vault.init.ModEntities.ELITE_ZOMBIE, 2.0)
                                            .entity(iskallia.vault.init.ModEntities.ELITE_SKELETON, 7.0)
                                            .entity(iskallia.vault.init.ModEntities.ELITE_WITHER_SKELETON, 1.0)
                                            .spawnRanges(1.0, 4.0)
                                            .build()
                                        )
                                        .task(new MessageTask(VaultEvent.EventDisplayType.ACTION_BAR, new TranslatableComponent("vault_event.woldsvaults.tombstone_elite").withStyle(ChatFormatting.DARK_PURPLE)))
                                        .build(), 4.0)
                                .task(new PlaySoundTask(SoundEvents.AMBIENT_CAVE, 1.0F, 0.6F, SoundSource.AMBIENT), 25.0)
                                .task(new TaskGroup.Builder()
                                        .task(new PlayerMobEffectTask.Builder()
                                                .effect(MobEffects.WITHER, 1, 200)
                                                .build()
                                        )
                                        .task(new PlaySoundTask(SoundEvents.SOUL_ESCAPE))
                                        .task(new MessageTask(VaultEvent.EventDisplayType.ACTION_BAR, new TranslatableComponent("vault_event.woldsvaults.tombstone_wither").withStyle(ChatFormatting.DARK_RED)))
                                        .build(),10.0)
                                .task(new TaskGroup.Builder()
                                        .task(new PlayerMobEffectTask.Builder()
                                                .effect(MobEffects.DIG_SLOWDOWN, 1, 300)
                                                .effect(MobEffects.MOVEMENT_SLOWDOWN, 2, 400)
                                                .build()
                                        )
                                        .task(new PlaySoundTask(SoundEvents.AMBIENT_CAVE))
                                        .task(new MessageTask(VaultEvent.EventDisplayType.ACTION_BAR, new TranslatableComponent("vault_event.woldsvaults.tombstone_weaken").withStyle(ChatFormatting.DARK_RED)))
                                        .build(),10.0)
                                .task(new TaskGroup.Builder()
                                        .task(new ExplosionTask(5.0F, Explosion.BlockInteraction.BREAK, true))
                                        .task(new MessageTask(VaultEvent.EventDisplayType.ACTION_BAR, new TranslatableComponent("vault_event.woldsvaults.tombstone_explode").withStyle(ChatFormatting.RED)))
                                        .build(),10.0)
                                .task(new TaskGroup.Builder()
                                        .task(new VaultModifierTask(VaultMod.id("cake_haunted"), 1))
                                        .task(new MessageTask(VaultEvent.EventDisplayType.CHAT_MESSAGE_TARGET, new TranslatableComponent("vault_event.woldsvaults.tombstone_soul_shard_increase").withStyle(ChatFormatting.LIGHT_PURPLE)))
                                        .task(new PlaySoundTask(SoundEvents.AMBIENT_CAVE))
                                        .build(), 10.0)
                                .task(new TaskGroup.Builder()
                                        .task(new VaultModifierTask(VaultMod.id("haunted_mansion"), 1, 1800))
                                        .task(new MessageTask(VaultEvent.EventDisplayType.ACTION_BAR, new TranslatableComponent("vault_event.woldsvaults.tombstone_haunted").withStyle(ChatFormatting.DARK_GRAY)))
                                        .task(new PlaySoundTask(SoundEvents.AMBIENT_CAVE))
                                        .build(), 2.0)
                                .task(new TaskGroup.Builder()
                                        .task(new VaultModifierTask(VaultMod.id("ethereal_mobs"), 1, 900))
                                        .task(new MessageTask(VaultEvent.EventDisplayType.ACTION_BAR, new TranslatableComponent("vault_event.woldsvaults.tombstone_ethereal").withStyle(ChatFormatting.DARK_AQUA)))
                                        .task(new PlaySoundTask(SoundEvents.AMBIENT_CAVE))
                                        .build(), 4.0)
                                .task(new TaskGroup.Builder()
                                        .task(new SpawnMobTask.Builder()
                                                .entity(ModEntities.GREEN_GHOST, 1)
                                                .entity(ModEntities.BROWN_GHOST, 1)
                                                .entity(ModEntities.RED_GHOST, 1)
                                                .entity(ModEntities.BLUE_GHOST, 1)
                                                .entity(ModEntities.YELLOW_GHOST, 1)
                                                .amount(3, 1)
                                                .amount(5, 1)
                                                .effect(new Effect(MobEffects.MOVEMENT_SPEED, 2, 400), 1)
                                                .build()
                                        )
                                        .task(new PlaySoundTask(SoundEvents.SOUL_ESCAPE))
                                        .task(new MessageTask(VaultEvent.EventDisplayType.ACTION_BAR, new TranslatableComponent("vault_event.woldsvaults.tombstone_spirits").withStyle(ChatFormatting.AQUA)))
                                        .build(),10.0)
                                .task(new TaskGroup.Builder()
                                        .task(new SpawnMobTask.Builder()
                                                .entity(iskallia.vault.init.ModEntities.T3_ZOMBIE, 1)
                                                .amount(1, 1)
                                                .effect(new Effect(MobEffects.MOVEMENT_SPEED, 2, 400), 1)
                                                .effect(new Effect(MobEffects.DAMAGE_RESISTANCE, 2, 400), 1)
                                                .effect(new Effect(MobEffects.DAMAGE_BOOST, 2, 400), 1)
                                                .spawnRanges(1.0, 4.0)
                                                .build()
                                        )
                                        .task(new PlaySoundTask(SoundEvents.AMBIENT_CAVE))
                                        .task(new MessageTask(VaultEvent.EventDisplayType.ACTION_BAR, new TranslatableComponent("vault_event.woldsvaults.tombstone_zombie").withStyle(ChatFormatting.DARK_GREEN)))
                                        .build(),15.0)
                                .task(new TaskGroup.Builder()
                                        .task(new SpawnMobTask.Builder()
                                                .entity(iskallia.vault.init.ModEntities.T3_SKELETON, 1)
                                                .entity(iskallia.vault.init.ModEntities.T3_BLOOD_SKELETON, 1)
                                                .entity(iskallia.vault.init.ModEntities.T3_CAVE_SKELETON, 1)
                                                .entity(iskallia.vault.init.ModEntities.T3_PLASTIC_SKELETON, 1)
                                                .entity(iskallia.vault.init.ModEntities.T3_WITHER_SKELETON, 1)
                                                .entity(iskallia.vault.init.ModEntities.T3_SKELETON_PIRATE, 1)
                                                .amount(1, 1)
                                                .amount(2, 1)
                                                .amount(3, 1)
                                                .effect(new Effect(MobEffects.MOVEMENT_SPEED, 2, 400), 1)
                                                .effect(new Effect(MobEffects.DAMAGE_BOOST, 2, 400), 1)
                                                .effect(new Effect(MobEffects.DAMAGE_RESISTANCE, 2, 400), 1)
                                                .spawnRanges(1.0, 4.0)
                                                .build()
                                        )
                                        .task(new PlaySoundTask(SoundEvents.AMBIENT_CAVE))
                                        .task(new MessageTask(VaultEvent.EventDisplayType.ACTION_BAR, new TranslatableComponent("vault_event.woldsvaults.tombstone_skeleton").withStyle(ChatFormatting.GRAY)))
                                        .build(),20.0)
                                .task(new TaskGroup.Builder()
                                        .task(new SpawnMobTask.Builder()
                                                .entity(EntityType.SKELETON_HORSE, 1)
                                                .amount(1, 1)
                                                .spawnRanges(1.0, 4.0)
                                                .build()
                                        )
                                        .task(new PlaySoundTask(SoundEvents.AMBIENT_CAVE))
                                        .task(new MessageTask(VaultEvent.EventDisplayType.ACTION_BAR, new TranslatableComponent("vault_event.woldsvaults.tombstone_horse").withStyle(ChatFormatting.LIGHT_PURPLE)))
                                        .build(),2.0)
                                .build()

                        )
                        .task(new DelayTask(20))
                        .task(new BlockConversionTask.Builder()
                                .replacementBlock(Blocks.DIRT.defaultBlockState(), 4)
                                .replacementBlock(Blocks.ROOTED_DIRT.defaultBlockState(), 2)
                                .replacementBlock(Blocks.STONE.defaultBlockState(), 1)
                                .replacementBlock(Blocks.COARSE_DIRT.defaultBlockState(), 2)
                                .replacementBlock(Blocks.ANDESITE.defaultBlockState(), 1)
                                .replacementBlock(Blocks.PODZOL.defaultBlockState(), 2)
                                .build(block -> block.equals(Blocks.BEDROCK)))
                        .task(new DelayTask(10))
                        .task(new BlockConversionTask.Builder().build(block -> block.equals(Blocks.BARRIER) || block.equals(Blocks.LECTERN)))

                .build("Tombstone", new TextComponent("Possible events that can occur when breaking a Tombstone.")));
    }
}
